export default {
  preset: 'ts-jest',
  clearMocks: true,
  collectCoverage: true,
  coverageReporters: ['text', 'json', 'json-summary', 'html', 'lcov'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/__tests__/',
    'dist/',
    '/.aws-sam/',
    'test/mocks/',
    '/testing',
    '.module.ts',
    '.dto.ts',
    '.entity.ts',
    'index.ts',
    '.decorator.ts',
    '.enum.ts',
    '.tokens.ts',
    'main.ts',
    'table.ts',
  ],
  detectOpenHandles: true,
  forceExit: true,
  logHeapUsage: true,
  verbose: true,
  setupFiles: ['./jest.env.js'],
  testTimeout: 30000,
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 80,
      lines: 85,
      statements: 85,
    },
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: './coverage',
  testEnvironment: 'node',
  roots: ['<rootDir>/src/', '<rootDir>/libs/'],
  moduleNameMapper: {
    '^@des/database(|/.*)$': '<rootDir>/libs/database/src/$1',
    '^@des/nova(|/.*)$': '<rootDir>/libs/nova/src/$1',
    '^@des/event-manager(|/.*)$': '<rootDir>/libs/event-manager/src/$1',
    '^@des/logger(|/.*)$': '<rootDir>/libs/logger/src/$1',
    '^@des/cache-manager(|/.*)$': '<rootDir>/libs/cache-manager/src/$1',
    '^@des/strapi(|/.*)$': '<rootDir>/libs/strapi/src/$1',
    '^@des/zoom(|/.*)$': '<rootDir>/libs/zoom/src/$1',
  },
  reporters: [
    'default',
    [
      './node_modules/jest-html-reporter',
      {
        pageTitle: 'Test Report',
        includeFailureMsg: true,
        includeConsoleLog: true,
      },
    ],
  ],
};
